### ISSUE TITLE
Classifying age

### ISSUE THREAD

**Issue by Zumbalamambo** [baileyfriend/Gender-Image-Classifier#2]
Is it possible to classify the age as well or is there any dataset apart from imdb and adience to do so since both are inaccurate?

**Comment by baileyfriend** [comment]
This project does not tackle the age classification problem, though it is an extremely interesting problem. I recommend you look at http://ieeexplore.ieee.org/document/6406650/ . In this study, they use an SVM instead of a recurrent neural network, but it has a similar effect. 

https://arxiv.org/pdf/1702.04280.pdf This study is more up to date, and uses automated systems (including a Deep Neural Network) to classify gender, age, and emotion. Really quite a fascinating read.
